name: publish-alpine3_12

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-alpine3_12:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read MariaDB version - minor
        uses: bfren/read-file-action@v1
        with:
          path: ./alpine3.12/MARIADB_MINOR
        id: mariadb_minor
      -
        name: Read MariaDB version - revision
        uses: bfren/read-file-action@v1
        with:
          path: ./alpine3.12/MARIADB_REVISION
        id: mariadb_revision
      -
        name: Read MariaDB version - build
        uses: bfren/read-file-action@v1
        with:
          path: ./alpine3.12/MARIADB_BUILD
        id: mariadb_build
      -
        name: Read image version
        uses: bfren/read-file-action@v1
        with:
          path: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./alpine3.12/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/mariadb:mariadb${{ steps.mariadb_minor.outputs.content }}
            bfren/mariadb:mariadb${{ steps.mariadb_minor.outputs.content }}-${{ steps.version.outputs.content }}
            bfren/mariadb:mariadb${{ steps.mariadb_revision.outputs.content }}
            bfren/mariadb:mariadb${{ steps.mariadb_revision.outputs.content }}-${{ steps.version.outputs.content }}
            bfren/mariadb:mariadb${{ steps.mariadb_build.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
